config/routes.rb
Rails.application.routes.draw do
  root 'people#index'
  resources :people
  resources :quotes
  resources :templates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/person.rb
class Person < ApplicationRecord
  has_one_attached :image
  has_many :quotes

  validates :name, presence: true, length: { maximum: 30 }
  validate :image_presence
  validate :image_content_type

  private

  def image_presence
    errors.add(:image, "can't be blank") unless image.attached?
  end

  def image_content_type
    if image.attached?
      unless image.content_type.in?(%w(image/jpeg image/png))
        errors.add(:image, 'must be a JPEG or PNG')
      end

      if image.blob.byte_size > 5.megabytes
        errors.add(:image, 'size exceeds 5MB')
      end
    end
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_one_attached :thumbnail
  belongs_to :person

  validates :content, presence: true, length: { maximum: 500 }
  validates :template, presence: true
end

app/models/template.rb
class Template < ApplicationRecord
  has_one_attached :picture

  validate :picture_presence
  validate :picture_content_type_and_size

  private

  def picture_presence
    errors.add(:picture, "can't be blank") unless picture.attached?
  end

  def picture_content_type_and_size
    if picture.attached?
      if !picture.content_type.in?(%w(image/jpeg image/png))
        errors.add(:picture, 'must be a JPEG or PNG')
      elsif picture.blob.byte_size > 5.megabytes
        errors.add(:picture, 'size exceeds 5MB')
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  def index
    @people = Person.all
  end

  def show
  end

  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @person.destroy!

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
    end
  end

  private
  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, :image)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]
  before_action :load_templates, only: [:new, :edit]

  def index
    @quotes = if params[:category].present? && params[:category] != "All"
      Quote.where(category: params[:category].downcase)
    else
      Quote.all.order(created_at: :desc)
    end
    @categories = Quote.distinct.pluck(:category).compact.map(&:capitalize)
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def edit
  end

  def create
    @quote = build_quote_with_defaults_and_author_name

    respond_to do |format|

      if @quote.save
        generate_thumbnail
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @quote.update(quote_params)
        # Update author name if person_id has changed
        if quote_params[:person_id] != @quote.person_id
          update_author_name
        end

        # Regenerate thumbnail if template_id has changed
        if quote_params[:template] != @quote.template
          generate_thumbnail
        end

        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @quote.destroy!

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
    end
  end

  private

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def generate_thumbnail
    GenerateThumbnailService.new(@quote).call
  end

  def build_quote_with_defaults_and_author_name
    # Create a new quote object with permitted parameters
    quote = Quote.new(quote_params)
    # Set default values for text properties
    set_default_values_for_quote_text(quote)
    # Set the selected template
    quote.template = params[:quote][:template]
    # Set the selected logo position
    quote.logo_position = params[:quote][:logo_position]
    # Set default logo position if none selected
    quote.logo_position = params[:quote][:logo_position].present? ? params[:quote][:logo_position] : 'bottom_right'
    # Set the selected template size
    quote.template_size = params[:quote][:template_size]
    # Set default template size if none selected
    quote.template_size = params[:quote][:template_size].present? ? params[:quote][:template_size] : '1300x500'
    #set the category for quote
    quote.category = params[:quote][:category]

    # Find the associated person and append their name to the author field
    person = Person.find_by(id: quote.person_id)
    quote.author = "-#{person.name}" if person
    quote
  end

  def load_templates
    @templates = Template.all
  end

  def set_default_values_for_quote_text(quote)
    quote.text_pointsize = quote.text_pointsize.present? ? quote.text_pointsize : 25
    quote.text_font = quote.text_font.present? ? quote.text_font : 'Arial'
    quote.text_fill = quote.text_fill.present? ? quote.text_fill : 'blue'
  end

  def update_author_name
    person = Person.find_by(id: @quote.person_id)
    @quote.update(author: "-#{person.name}") if person
  end

  def quote_params
    params.require(:quote).permit(:content, :author, :person_id, :thumbnail, :logo_path, :template, :text_pointsize, :text_font, :text_fill, :logo_position, :template_size, :category)
  end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :set_template, only: %i[ show edit update destroy ]

  def index
    @templates = Template.all
  end

  def show
  end

  def new
    @template = Template.new
  end

  def edit
  end

  def create
    @template = Template.new(template_params)

    respond_to do |format|
      if @template.save
        format.html { redirect_to template_url(@template), notice: "Template was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @template.update(template_params)
        format.html { redirect_to template_url(@template), notice: "Template was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @template.destroy!

    respond_to do |format|
      format.html { redirect_to templates_url, notice: "Template was successfully destroyed." }
    end
  end

  private

  def set_template
    @template = Template.find(params[:id])
  end

  def template_params
    params.require(:template).permit(:picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/quote_templates_helper.rb
module QuoteTemplatesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div><br>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <%= person.name %>
  </p>

  <p>
    <%= link_to image_tag(person.image, style:"width:150px; height:150px"), person.image %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %><br>

<div>
  <button onclick="location.href='<%= people_path %>';">Back To People</button>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>People</h1>

<button onclick="location.href='<%= new_person_path %>'">Person</button>&nbsp;
<button onclick="location.href='<%= quotes_path %>'">Quote</button>&nbsp;
<button onclick="location.href='<%= templates_path %>'">Template</button><br><br>

<div id="people">
  <% @people.each do |person| %>
    <div class="person-container">
      <%= render person %>
      <p>
        <button onclick="location.href='<%= person_path(person) %>';">Show Person</button>
      </p>
    </div>
  <% end %>
</div>

app/views/people/new.html.erb
<h1>Add Person</h1>

<%= render "form", person: @person %><br>

<button onclick="location.href='<%= people_path %>';">Back To People</button>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <button onclick="location.href='<%= edit_person_path(@person) %>';">Edit Person</button>&nbsp;
  <button onclick="location.href='<%= people_path %>';">Back To People</button><br>&nbsp;
  <%= button_to "Destroy Person", @person, method: :delete %>
</div>

app/views/quotes/_form.html.erb
<%= form_with(model: quote) do |form| %>
  <% if quote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :person_id, "Select Person", style: "display: block" %>
    <%= form.collection_select :person_id, Person.all, :id, :name, prompt: "Select Person" %>
  </div><br>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div><br>

  <div>
    <%= form.label :category, "Select Quote Category" %><br>
    <%= form.select :category, [['Motivational', 'motivational'], ['Humorous', 'humorous'], ['Inspirational', 'inspirational'], ['Educational', 'educational'], ['Adventure', 'adventure'], ['Romantic', 'romantic'], ['Action', 'action'], ['Mystery', 'mystery'], ['Fantasy', 'fantasy'], ['Historical', 'historical'], ['Biographical', 'biographical'], ['Science Fiction', 'science_fiction'], ['Thriller', 'thriller'], ['Horror', 'horror'], ['Drama', 'drama'], ['Comedy', 'comedy']], prompt: "Select Category" %>
  </div><br>

  <div>
    <%= form.label :text_pointsize, "Select Text Size" %><br>
    <%= form.number_field :text_pointsize, min: 1, max: 50, step: 1 %>
  </div><br>

  <div>
    <%= form.label :text_font, "Select Text Font Style" %><br>
    <%= form.collection_select :text_font,
                              [['Arial', 'Arial'],
                              ['Times New Roman', 'Times New Roman'],
                              ['Verdana', 'Verdana'],
                              ['Helvetica', 'Helvetica'],
                              ['Georgia', 'Georgia'],
                              ['Courier New', 'Courier New'],
                              ['Tahoma', 'Tahoma'],
                              ['Palatino', 'Palatino'],
                              ['Lucida Sans', 'Lucida Sans'],
                              ['Garamond', 'Garamond'],
                              ['Bookman', 'Bookman'],
                              ['Trebuchet MS', 'Trebuchet MS']],
                             :last, :first,
                             prompt: "Select Font Style" %>
  </div><br>

  <div>
    <%= form.label :text_fill, "Select Text Color" %><br>
    <%= form.collection_select :text_fill,
                              [['Red', 'red'],
                              ['Blue', 'blue'],
                              ['Green', 'green'],
                              ['Black', 'black'],
                              ['White', 'white'],
                              ['Yellow', 'yellow'],
                              ['Orange', 'orange'],
                              ['Purple', 'purple'],
                              ['Pink', 'pink'],
                              ['Gray', 'gray'],
                              ['Brown', 'brown'],
                              ['Cyan', 'cyan']],
                             :last, :first,
                             prompt: "Select Color" %>
  </div><br>

  <div>
    <%= form.label :logo_position, "Select Person Logo Position" %><br>
    <%= form.collection_select :logo_position, [['Top Right', 'top_right'],
                                              ['Top Center', 'top_center'],
                                              ['Top Left', 'top_left'],
                                              ['Right Center', 'right_center'],
                                              ['Bottom Right', 'bottom_right'],
                                              ['Bottom Center', 'bottom_center'],
                                              ['Bottom Left', 'bottom_left'],
                                              ['Left Center', 'left_center'],
                                              ['Center', 'center']], :last, :first, prompt: "Select Logo Position" %>
  </div><br>

  <div id="template-selector">
    <%= form.label :template, "Select Template" %>
    <% if @templates.present? %>
      <% @templates.each do |template| %>
        <div>
          <%= form.radio_button :template, template.id %>
          <%= form.label template.id do %>
            <%= image_tag template.picture, size: '80x80'%>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p>No templates available.</p>
    <% end %>
  </div><br>


  <div>
    <%= form.label :template_size, "Select Template Size" %><br>
    <%= form.collection_select :template_size,
                             [['500 x 300', '500x300'],
                              ['600 x 400', '600x400'],
                              ['700 x 500', '700x500'],
                              ['800 x 600', '800x600'],
                              ['900 x 500', '900x500'],
                              ['1000 x 500', '1000x500'],
                              ['1100 x 500', '1100x500'],
                              ['1200 x 500', '1200x500'],
                              ['1300 x 500', '1300x500'],
                              ['1024 x 768', '1024x768'],
                              ['1250 x 720', '1250x720'],
                              ['1300 x 768', '1300x768'],
                              ['1350 x 800', '1350x800']],
                             :last, :first, prompt: "Select Template Size" %>
  </div><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/_quote.html.erb
<div id="<%= dom_id quote %>">
  <% if quote.thumbnail.attached? %>
    <%= image_tag quote.thumbnail %>
  <% else %>
    <p>No thumbnail available</p>
  <% end %>
</div>

app/views/quotes/edit.html.erb
<h1>Edit Quote</h1>

<%= render "form", quote: @quote %><br>

<div>
  <button onclick="location.href='<%= quote_path(@quote) %>';">Show Quote</button>&nbsp;
  <button onclick="location.href='<%= quotes_path %>';">Back To Quotes</button>
</div>

app/views/quotes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quotes</h1>

<div>
  <button onclick="location.href='<%= people_path %>';">Back To People</button>
</div><br>

<button onclick="location.href='<%= new_quote_path %>';">Add Quote</button><br><br>

<% if @categories.present? %>
  <%= form_tag(quotes_path, method: "get") do %>
    <%= select_tag :category, options_for_select(['All'] + @categories.map(&:capitalize)), prompt: "Select Quote Category" %>
    <%= submit_tag "Search" %>
  <% end %>
<% end %>

<% if params[:category].present? && params[:category] != "All" %>
  <% selected_category = params[:category].downcase %>
  <h2><%= selected_category.capitalize %> Quotes</h2>
  <div id="<%= selected_category %>-quotes">
    <% @quotes.each do |quote| %>
      <%= render quote %>
      <p>
        <button onclick="location.href='<%= quote_path(quote) %>';">Show Quote</button>
      </p>
    <% end %>
  </div>
<% else %>
  <h2>All Quotes</h2>
  <div id="all-quotes">
    <% @quotes.each do |quote| %>
      <%= render quote %>
      <p>
        <button onclick="location.href='<%= quote_path(quote) %>';">Show Quote</button>
      </p>
    <% end %>
  </div>
<% end %>

app/views/quotes/new.html.erb
<h1>Add Quote</h1>

<%= render "form", quote: @quote %><br>

<div>
  <button onclick="location.href='<%= quotes_path %>';">Back To Quotes</button>
</div>

app/views/quotes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quote %>

<div>
  <button onclick="location.href='<%= edit_quote_path(@quote) %>';">Edit Quote</button>&nbsp;
  <button onclick="location.href='<%= quotes_path %>';">Back To Quotes</button><br>&nbsp;
  <%= button_to "Destroy Quote", @quote, method: :delete %>
</div>

app/views/templates/_form.html.erb
<%= form_with(model: template) do |form| %>
  <% if template.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
        <% template.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/templates/_template.html.erb
<div id="<%= dom_id template %>">
  <%= link_to image_tag(template.picture, style:"width:600px; height:350px"), template.picture %>
</div>

app/views/templates/edit.html.erb
<h1>Edit Template</h1>

<%= render "form", template: @template %><br>

<div>
  <button onclick="location.href='<%= template_path(@template) %>';">Show Template</button>&nbsp;
  <button onclick="location.href='<%= templates_path %>';">Back To Templates</button>
</div>

app/views/templates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Templates</h1>

<div>
  <button onclick="location.href='<%= people_path %>';">Back To People</button>
</div><br>

<button onclick="location.href='<%= new_template_path %>';">Add Template</button><br><br>

<div id="templates">
  <% @templates.each do |template| %>
    <%= render template %>
    <p>
      <button onclick="location.href='<%= template_path(template) %>';">Show Template</button>
    </p>
  <% end %>
</div>

app/views/templates/new.html.erb
<h1>Add Template</h1>

<%= render "form", template: @template %><br>

<div>
  <button onclick="location.href='<%= templates_path %>';">Back To Templates</button>
</div>

app/views/templates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @template %>

<div>
  <button onclick="location.href='<%= edit_template_path(@template) %>';">Edit Template</button>&nbsp;
  <button onclick="location.href='<%= templates_path %>';">Back To Templates</button><br>&nbsp;
  <%= button_to "Destroy Template", @template, method: :delete %>
</div>